import { test } from 'node:test';
import assert from 'node:assert/strict';
import { periodBounds, shiftPeriod, entriesInPeriod, summarize, timeline, mutationSchema, defaults, type Entry } from '../src/journal.ts';
const entry = (when: string, choice: Entry['choice'] = 'plan'): Entry => ({ id: crypto.randomUUID(), categoryId: 'scrolling', categoryLabel: 'Scrolling', choice, mode: 'moment', occurredAt: new Date(when).toISOString(), recordedAt: new Date().toISOString(), note: '' });
test('weeks start Monday and exclude the following Monday', () => { const a = new Date(2026, 9, 11, 12), { start, end } = periodBounds(a, 'week'); assert.equal(start.getDate(), 5); assert.equal(end.getDate(), 12); const rows = [entry('2026-10-05T00:00:00'), entry('2026-10-11T23:59:59', 'original'), entry('2026-10-12T00:00:00')]; assert.deepEqual(summarize(entriesInPeriod(rows, a, 'week')), { total: 2, plan: 1, original: 1, rate: 50 }); });
test('calendar month navigation avoids overflow on the 31st', () => { const shifted = shiftPeriod(new Date(2026, 2, 31), 'month', -1); assert.equal(shifted.getMonth(), 1); assert.equal(shifted.getDate(), 1); const { end } = periodBounds(shifted, 'month'); assert.equal(end.getMonth(), 2); });
test('daylight saving week retains seven calendar days', () => { const anchor = new Date(2026, 2, 8), { start, end } = periodBounds(anchor, 'week'); assert.equal(start.getDate(), 2); assert.equal(end.getDate(), 9); const rows = [entry('2026-03-08T03:10:00'), entry('2026-03-09T00:00:00')]; assert.equal(entriesInPeriod(rows, anchor, 'week').length, 1); assert.equal(timeline(rows, anchor, 'week').length, 7); });
test('month timeline assigns each recorded choice exactly once', () => { const rows = [entry('2026-10-01T00:00:00'), entry('2026-10-07T23:59:59'), entry('2026-10-08T00:00:00', 'original'), entry('2026-10-31T23:59:59'), entry('2026-11-01T00:00:00')]; const bins = timeline(rows, new Date(2026, 9, 15), 'month'); assert.equal(bins.reduce((sum, b) => sum + b.total, 0), 4); assert.equal(bins[0].total, 2); assert.equal(bins[1].original, 1); assert.equal(bins.at(-1)?.label, '29–31'); });
test('empty journals never imply perfect or failed choices', () => { assert.equal(summarize([]).rate, null); assert.equal(summarize([]).total, 0); });
test('input validation rejects future dates, invalid choices, oversized notes and duplicate category IDs', () => { const valid = { action: 'record', ...entry('2025-10-01T15:00:00') }; assert.equal(mutationSchema.safeParse(valid).success, true); for (const patch of [{ choice: 'unknown' }, { occurredAt: new Date(Date.now() + 86400000).toISOString() }, { note: 'x'.repeat(1001) }])
    assert.equal(mutationSchema.safeParse({ ...valid, ...patch }).success, false); assert.equal(mutationSchema.safeParse({ action: 'settings', settings: { ...defaults, categories: [defaults.categories[0], defaults.categories[0]] } }).success, false); });
