import {legacyCategories,foodIds,entriesByDirection,guidanceFor} from '../src/journal.ts';
import {settingsSchema,chooseEncouragement} from '../src/journal.ts';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { periodBounds, shiftPeriod, entriesInPeriod, summarize, timeline, mutationSchema, defaults, type Entry } from '../src/journal.ts';
const entry = (when: string, choice: Entry['choice'] = 'plan'): Entry => ({ id: crypto.randomUUID(), categoryId: 'scrolling', categoryLabel: 'Scrolling', choice, mode: 'moment', occurredAt: new Date(when).toISOString(), recordedAt: new Date().toISOString(), note: '' });
test('weeks start Monday and exclude the following Monday', () => { const a = new Date(2026, 9, 11, 12), { start, end } = periodBounds(a, 'week'); assert.equal(start.getDate(), 5); assert.equal(end.getDate(), 12); const rows = [entry('2026-10-05T00:00:00'), entry('2026-10-11T23:59:59', 'original'), entry('2026-10-12T00:00:00')]; assert.deepEqual(summarize(entriesInPeriod(rows, a, 'week')), { total: 2, plan: 1, original: 1, rate: 50 }); });
test('calendar month navigation avoids overflow on the 31st', () => { const shifted = shiftPeriod(new Date(2026, 2, 31), 'month', -1); assert.equal(shifted.getMonth(), 1); assert.equal(shifted.getDate(), 1); const { end } = periodBounds(shifted, 'month'); assert.equal(end.getMonth(), 2); });
test('daylight saving week retains seven calendar days', () => { const anchor = new Date(2026, 2, 8), { start, end } = periodBounds(anchor, 'week'); assert.equal(start.getDate(), 2); assert.equal(end.getDate(), 9); const rows = [entry('2026-03-08T03:10:00'), entry('2026-03-09T00:00:00')]; assert.equal(entriesInPeriod(rows, anchor, 'week').length, 1); assert.equal(timeline(rows, anchor, 'week').length, 7); });
test('month timeline assigns each recorded choice exactly once', () => { const rows = [entry('2026-10-01T00:00:00'), entry('2026-10-07T23:59:59'), entry('2026-10-08T00:00:00', 'original'), entry('2026-10-31T23:59:59'), entry('2026-11-01T00:00:00')]; const bins = timeline(rows, new Date(2026, 9, 15), 'month'); assert.equal(bins.reduce((sum, b) => sum + b.total, 0), 4); assert.equal(bins[0].total, 2); assert.equal(bins[1].original, 1); assert.equal(bins.at(-1)?.label, '29–31'); });
test('empty journals never imply perfect or failed choices', () => { assert.equal(summarize([]).rate, null); assert.equal(summarize([]).total, 0); });
test('input validation rejects future dates, invalid choices, oversized notes and duplicate category IDs', () => { const valid = { action: 'record', ...entry('2025-10-01T15:00:00') }; assert.equal(mutationSchema.safeParse(valid).success, true); for (const patch of [{ choice: 'unknown' }, { occurredAt: new Date(Date.now() + 86400000).toISOString() }, { note: 'x'.repeat(1001) }])
    assert.equal(mutationSchema.safeParse({ ...valid, ...patch }).success, false); assert.equal(mutationSchema.safeParse({ action: 'settings', settings: { ...defaults, categories: [defaults.categories[0], defaults.categories[0]] } }).success, false); });

test('legacy settings preserve custom encouragement while adding phrase options',()=>{const {encouragements:_,...legacy}=defaults;const result=settingsSchema.parse({...legacy,headline:'Remember my own plan.'});assert.equal(result.encouragements[0],'Remember my own plan.');assert.ok(result.encouragements.length>1);assert.equal(result.recipe[0].title,legacy.recipe[0].title);});
test('encouragement selection avoids an immediate repeat and supports a single phrase',()=>{assert.equal(chooseEncouragement(['One','Two'],'One',()=>0),'Two');assert.equal(chooseEncouragement(['One'],'One',()=>0),'One');assert.equal(chooseEncouragement(['One','One'],'One',()=>0),'One');});
test('phrase lists require at least one nonempty option',()=>{for(const encouragements of [[],[' '],Array(21).fill('Too many')])assert.equal(settingsSchema.safeParse({...defaults,encouragements}).success,false);});

test('Pause has exactly the seven approved positive directions',()=>{assert.deepEqual(defaults.categories.map(c=>c.label),['Be Present','Eat Well','Rest Well','Be Kind to Myself','Start My Day','Use My Time Well','Move Well']);assert.ok(defaults.categories.every(c=>c.encouragement&&c.guidance));});
test('legacy buttons merge into Eat Well while retaining custom directions and visibility',()=>{const {directionsVersion:_,...old}=defaults;const custom={id:'custom',label:'Make music',image:'splash-recipe-v2.webp',active:true};const migrated=settingsSchema.parse({...old,categories:[...legacyCategories.map(c=>({...c,active:c.id!=='scrolling'})),custom]});assert.equal(migrated.categories.length,8);assert.equal(migrated.categories.filter(c=>c.label==='Eat Well').length,1);assert.equal(migrated.categories.find(c=>c.id==='scrolling')?.active,false);assert.deepEqual(migrated.categories.at(-1),{...custom,alternatives:[]});assert.deepEqual(settingsSchema.parse(migrated),migrated);});
test('all hidden food buttons produce a hidden combined button',()=>{const {directionsVersion:_,...old}=defaults;const upgraded=settingsSchema.parse({...old,categories:legacyCategories.map(c=>({...c,active:!foodIds.has(c.id)}))});assert.equal(upgraded.categories.find(c=>c.id==='eat-well')?.active,false);});
test('historical food entries aggregate with new entries without mutating their originals',()=>{const rows=['seconds','junk-food','unplanned-eating','eat-well'].map((id,i)=>({...entry('2026-10-01T12:00:00',i===0?'original':'plan'),categoryId:id,categoryLabel:id}));const copy=structuredClone(rows);const report=entriesByDirection(rows,defaults.categories);assert.ok(report.every(e=>e.categoryId==='eat-well'&&e.categoryLabel==='Eat Well'));assert.deepEqual(summarize(report),{total:4,plan:3,original:1,rate:75});assert.deepEqual(rows,copy);});
test('specific guidance starts with the approved reminder; custom directions have a fallback',()=>{const move=defaults.categories.find(c=>c.id==='move-well')!;assert.equal(guidanceFor(move,defaults).encouragement,'You don’t have to feel motivated to begin.');assert.match(guidanceFor(move,defaults).guidance,/Put on your workout clothes/);assert.equal(guidanceFor({id:'custom',label:'Create',image:'',active:true},defaults).guidance,defaults.reminder);});

test('missing alternatives receive five defaults without replacing edited or empty lists',()=>{
 const old={...defaults,categories:defaults.categories.map(({alternatives,...c})=>c)};
 const migrated=settingsSchema.parse(old);
 assert.ok(migrated.categories.every(c=>c.alternatives?.length===5));
 const customized=settingsSchema.parse({...old,categories:[{...old.categories[0],label:'My attention',active:false,alternatives:['Call my sister']},{...old.categories[1],alternatives:[]},{id:'custom',label:'Create',image:'',active:true}]});
 assert.deepEqual(customized.categories[0].alternatives,['Call my sister']);
 assert.equal(customized.categories[0].active,false);
 assert.deepEqual(customized.categories[1].alternatives,[]);
 assert.deepEqual(customized.categories[2].alternatives,[]);
 assert.equal(settingsSchema.safeParse({...defaults,categories:[{...defaults.categories[0],alternatives:[' ']}]}).success,false);
});
