import {useState} from 'react';
import {readJournal,makeBackup,parseBackup,importBackup,type Backup} from './storage';
export default function DeviceTools({onImported}:{onImported:()=>Promise<void>}){
 const [message,setMessage]=useState(''),[backup,setBackup]=useState<Backup|null>(null),[restore,setRestore]=useState(false),[busy,setBusy]=useState(false);
 async function exportData(){setBusy(true);setMessage('');try{
  const journal=await readJournal(),contents=JSON.stringify(makeBackup(journal),null,2),name=`steer-backup-${new Date().toISOString().slice(0,10)}.json`,file=new File([contents],name,{type:'application/json'});
  if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Steer journal backup'});setMessage('Backup handed to the share sheet. If you saved it, check Files for your backup.');}
  else{const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setMessage('Backup download started. Check Files or Downloads for the saved file.');}
 }catch(e){setMessage((e as Error).name==='AbortError'?'Backup canceled. Your journal is still saved in Steer.':'Could not export the backup. Your journal is unchanged.');}finally{setBusy(false);}}
 async function chooseFile(file?:File){setBackup(null);setMessage('');if(!file)return;if(file.size>20_000_000){setMessage('Choose a Steer backup under 20 MB.');return;}try{setBackup(parseBackup(await file.text()));}catch(e){setMessage((e as Error).message);}}
 async function restoreBackup(){if(!backup)return;setBusy(true);try{const count=await importBackup(backup,restore);await onImported();setBackup(null);setMessage(`Restored ${count} new ${count===1?'choice':'choices'}. Existing entries were kept.`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="device-tools"><h2>On this device</h2><p>Your choices, notes, and reminders stay here. They aren’t sent to GitHub or a server.</p><details><summary>Add Steer to my Home Screen</summary><ol><li>Open this site in Safari on your iPhone.</li><li>Tap Share, then Add to Home Screen.</li><li>Turn on Open as Web App if shown, then tap Add.</li><li>Open the Steer icon and use that app for your journal.</li></ol><p className="small">Set this up before you start logging. Another browser, device, or website address can have a separate journal. The app works offline after its first successful download.</p></details><details><summary>Back up or restore my journal</summary><p>Clearing website data or removing the app can erase your journal. Keep a backup you can restore.</p><button className="secondary" disabled={busy} onClick={()=>void exportData()}>Export backup to Files</button><p className="small">On iPhone, choose Save to Files → On My iPhone to keep the backup local. The file contains your personal journal. Export after important changes.</p><label className="field">Restore a Steer backup<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{void chooseFile(e.target.files?.[0]);e.target.value='';}}/></label>{backup&&<div className="restore-preview"><strong>{backup.entries.length} choices in this backup</strong><p>New entries will be added. Existing entries with the same ID will be kept.</p><label className="check-label"><input type="checkbox" checked={restore} onChange={e=>setRestore(e.target.checked)}/>Also replace my reminders with the backup’s reminders</label><button disabled={busy} className="primary" onClick={()=>void restoreBackup()}>{busy?'Restoring…':'Restore on this device'}</button><button disabled={busy} className="text-button" onClick={()=>setBackup(null)}>Cancel</button></div>}</details>{message&&<p className="device-message" role="status">{message}</p>}</div>;
}
